### ISSUE TITLE
Handling Maven Inheritence

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/vertx-maven-plugin#33]
Does Maven project methods .getDependencies() and getPlugins() handles inheritance ?

**Comment by rhuss** [comment]
Do you mean (a) inheritance from a parent pom or (b) transitive dependencies coming from other dependencies ? For (a) the deps are included since Maven creates an effective pom mergin in all infos from the parent. For (b) I'm pretty sure that its the case (but not 100%). But that can be easily tested.

**Comment by kameshsampath** [comment]
yes @rhuss, i just hit with a bug which I closed via #38 as I saw the `setup` mojo writing back the effective pom.  I handled it by getting the mavenProject#getOriginalModel which gives you the non-effective pom. The idea is to update the MojoUtils#hasPlugin and MojoUtils#hasDependency to use the effective pom to identify the plugins correctly including the inherited ones.

**Comment by kameshsampath** [comment]
closing this via @cescoffier #45
